@startuml
package fr.parisNanterre.iqplaylib.api {

interface IAnswer {
    + String answer()
}

interface IGame {
    + String name()
    + IGameSession createSession() throws SessionAlreadyExistsException
}

interface IGameSession {
    + void start()
    + void pause()
    + void end()
    + IQuestion nextQuestion()
    + void submitAnswer(IPlayerAnswer answer)
}

interface IQuestion {
    + String question()
    + ICorrectAnswer correctAnswer()
}

interface IScore {
    + int score()
    + void incrementScore(int value)
}

}

package fr.parisNanterre.iqplaylib.core {

class CorrectAnswer implements ICorrectAnswer {
    - String answerText
    + CorrectAnswer(String answerText)
    + String answer()
}

class Game extends AbstractGame {
    + Game(String name)
}

class GameSession extends AbstractGameSession {
    + GameSession(IGame game)
}

class Question implements IQuestion {
    - String questionText
    - ICorrectAnswer correctAnswer
    + Question(String questionText, ICorrectAnswer correctAnswer)
    + String question()
    + ICorrectAnswer correctAnswer()
}

class Score implements IScore {
    - int scoreValue
    + Score()
    + int score()
    + void incrementScore(int value)
}

class SessionAlreadyExistsException extends RuntimeException {
    + SessionAlreadyExistsException(String message)
}
}
@enduml