name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
      - develop

permissions:
  packages: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Read version from build.gradle
        id: read-version
        run: |
          ls -alh lib/
          VERSION=$(grep -oP 'version = "\K[^"]+' lib/build.gradle)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          BUILD_NUMBER=${VERSION}
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -PbuildNumber=${{ env.BUILD_NUMBER }}
