name: Build and Upload Doxygen

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Doxygen + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Zip documentation
        run: zip -r doxygen-doc.zip docs

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create or update GitHub Release and upload documentation
        run: |
          gh release create ${{ github.ref }} doxygen-doc.zip --clobber --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
