name: Build and Upload Doxygen

on:
  release:
    types:
      - created

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Doxygen + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Zip documentation
        run: zip -r doxygen-doc.zip docs

      - name: Upload Doxygen documentation to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: doxygen-doc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
